# Generated by Django 5.1.1 on 2024-09-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users_remove_toys_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Toys',
        ),
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
